# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/machine_learning_blog/',
                'doc_host': 'https://joaopcnogueira.github.io',
                'git_url': 'https://github.com/joaopcnogueira/machine-learning-blog/',
                'lib_path': 'machine_learning_blog'},
  'syms': { 'machine_learning_blog.cli': { 'machine_learning_blog.cli.build_lib': ('cli.html#build_lib', 'machine_learning_blog/cli.py'),
                                           'machine_learning_blog.cli.hello_blog': ('cli.html#hello_blog', 'machine_learning_blog/cli.py')},
            'machine_learning_blog.core': { 'machine_learning_blog.core.hi_machine': ( 'o_que_e_machine_learning.html#hi_machine',
                                                                                       'machine_learning_blog/core.py')}}}
