# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_cli.ipynb.

# %% auto 0
__all__ = ['hello_blog', 'build_lib']

# %% ../nbs/02_cli.ipynb 2
import os
from fastcore.script import call_parse, Param

# %% ../nbs/02_cli.ipynb 4
@call_parse
def hello_blog(to: Param("to who gives hello", str)="João"):
    "Just say hello"
    return f"Hello {to}!"

# %% ../nbs/02_cli.ipynb 5
@call_parse
def build_lib():
    "Build the lib and generate the .whl file"
    os.system("python setup.py bdist_wheel")
