# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_o_que_e_machine_learning.ipynb.

# %% auto 0
__all__ = ['hi_machine']

# %% ../nbs/01_o_que_e_machine_learning.ipynb 1
def hi_machine():
    return "Hi Human!"
